2024-05-23 18:06:58,024 INFO    MainThread:91432 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-23 18:06:58,025 INFO    MainThread:91432 [wandb_setup.py:_flush():76] Configure stats pid to 91432
2024-05-23 18:06:58,025 INFO    MainThread:91432 [wandb_setup.py:_flush():76] Loading settings from /home/mhm/.config/wandb/settings
2024-05-23 18:06:58,025 INFO    MainThread:91432 [wandb_setup.py:_flush():76] Loading settings from /home/mhm/workspace/Competition_TaxingAI/wandb/settings
2024-05-23 18:06:58,025 INFO    MainThread:91432 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-23 18:06:58,025 INFO    MainThread:91432 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-23 18:06:58,025 INFO    MainThread:91432 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'TaxAI_modified/main.py', 'program_abspath': '/home/mhm/workspace/Competition_TaxingAI/TaxAI_modified/main.py', 'program': '/home/mhm/workspace/Competition_TaxingAI/TaxAI_modified/main.py'}
2024-05-23 18:06:58,025 INFO    MainThread:91432 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-23 18:06:58,025 INFO    MainThread:91432 [wandb_init.py:_log_setup():520] Logging user logs to /home/mhm/workspace/Competition_TaxingAI/wandb/run-20240523_180658-tze8adr6/logs/debug.log
2024-05-23 18:06:58,025 INFO    MainThread:91432 [wandb_init.py:_log_setup():521] Logging internal logs to /home/mhm/workspace/Competition_TaxingAI/wandb/run-20240523_180658-tze8adr6/logs/debug-internal.log
2024-05-23 18:06:58,025 INFO    MainThread:91432 [wandb_init.py:init():560] calling init triggers
2024-05-23 18:06:58,025 INFO    MainThread:91432 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-05-23 18:06:58,025 INFO    MainThread:91432 [wandb_init.py:init():610] starting backend
2024-05-23 18:06:58,025 INFO    MainThread:91432 [wandb_init.py:init():614] setting up manager
2024-05-23 18:06:58,027 INFO    MainThread:91432 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-05-23 18:06:58,029 INFO    MainThread:91432 [wandb_init.py:init():622] backend started and connected
2024-05-23 18:06:58,033 INFO    MainThread:91432 [wandb_init.py:init():711] updated telemetry
2024-05-23 18:06:58,041 INFO    MainThread:91432 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-23 18:06:58,697 INFO    MainThread:91432 [wandb_run.py:_on_init():2396] communicating current version
2024-05-23 18:06:58,903 INFO    MainThread:91432 [wandb_run.py:_on_init():2405] got version response 
2024-05-23 18:06:58,903 INFO    MainThread:91432 [wandb_init.py:init():795] starting run threads in backend
2024-05-23 18:07:03,378 WARNING MsgRouterThr:91432 [router.py:message_loop():77] message_loop has been closed
2024-05-23 18:07:08,909 ERROR   MainThread:91432 [wandb_init.py:init():1174] error in wandb.init()
Traceback (most recent call last):
  File "/home/mhm/anaconda3/envs/taxingai-venv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
  File "/home/mhm/anaconda3/envs/taxingai-venv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 808, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/home/mhm/anaconda3/envs/taxingai-venv/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 281, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
